### PR TITLE
fix/download: use https to avoid dealing with 301 headers

### LINKED ISSUE #10: No traffic on download
When I run the `load-dataset` command, I don't get an error, but I don't get any incoming traffic.

Example from running `sudo nethogs`:

```
 9336 user     target/debug/juice-examples tun0       0.000       0.000 KB/sec
```

```
    Finished dev [unoptimized + debuginfo] target(s) in 7.89 secs
     Running `target/debug/juice-examples load-dataset fashion`
Downloading... 1/4: train-images-idx3-ubyte.gz
URL: http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/train-images-idx3-ubyte.gz
```

This happens with the MNIST set too. I have to use `wget` to deposit the files in the folder manually.

### PR DESCRIPTION
**Pull request by drahnr**
Closes #10

### CODE REVIEW

**Comment by subversive-owl** [comment]
i feel merge conflicts coming on... :p

**Comment by drahnr** [comment]
Yep, definitley - but in this case no big deal

**Comment by drahnr** [comment]
@subversive-owl please check if this still works as intended.

**Comment by subversive-owl** [comment]
I think the download is breaking on fashion-MNIST. Updating shortly with MD5 hashes...

### hashes of program download

```
7edbbf1fc824916c442268ac4dc845cd  - ./t10k-images-idx3-ubyte.gz.md5
b9859d5936603c782c6eb8dd14198360  - ./t10k-labels-idx1-ubyte.gz.md5
053aba987904a004d52cb333753041a3  - ./train-images-idx3-ubyte.gz.md5
7864864ad9592b0ffcc53c942eb67b24  - ./train-labels-idx1-ubyte.gz.md5
```

### manually downloaded from repo S3 link

```
7edbbf1fc824916c442268ac4dc845cd  - ./t10k-images-idx3-ubyte.gz.md5
b9859d5936603c782c6eb8dd14198360  - ./t10k-labels-idx1-ubyte.gz.md5
053aba987904a004d52cb333753041a3  - ./train-images-idx3-ubyte.gz.md5
7864864ad9592b0ffcc53c942eb67b24  - ./train-labels-idx1-ubyte.gz.md5
```

### downloaded from repo directly

```
bef4ecab320f06d8554ea6380940ec79  - ./t10k-images-idx3-ubyte.gz.md5
bb300cfdad3c16e7a12a480ee83cd310  - ./t10k-labels-idx1-ubyte.gz.md5 
8d4fb7e6c68d591d4c3dfef9ec88bf0d  - ./train-images-idx3-ubyte.gz.md5
25c81989df183df01b3e8a0aad5dffbe  - ./train-labels-idx1-ubyte.gz.md5
```

It looks like the S3 bucket is not providing files properly.

**Review by subversive-owl — DISMISSED** [review]
Looks good. I did a little bit of cleanup while testing possible download issues, but it seems like all the troubles are at the other repo.

**Comment by subversive-owl** [comment]
The MNIST downloader seems to be cutting off the data sets, because it drops it before it reaches full size.

### program downloaded hashes

```
16814998f5124c5092453d508909bfc1  - ./mnist_test.csv.md5
3d9943019997692dd4faf72b7469d52c  - ./mnist_train.csv.md5
```

### manually downloaded hashes

```
c807df8d6d804ab2647fc15c3d40f543  - ./mnist_test.csv.md5 
5b49cf1b57fb9d6102b559d59d99df7c  - ./mnist_train.csv.md5
```

**Comment by drahnr** [comment]
@subversive-owl see #13 for a final resolution, I have yet to rebase it

**Pull request merged**
